# CSC configuration for teax
# Generated by scaffold-existing

# Project metadata
CSC_PROJECT_NAME="Teax"
CSC_PROJECT_DESC="python project"

# Output control - customize as needed
CSC_SHOW_TREE=true
CSC_SHOW_STATS=true
CSC_INCLUDE_EXAMPLES=false
CSC_INCLUDE_TESTS=false

# File handling
CSC_MAX_FILE_SIZE=100000  # 100KB default
CSC_MAX_DEPTH=4

# Additional exclude patterns (space-separated)
# CSC_EXCLUDE_PATTERNS="*.log *.tmp"

# Custom file priority (lower number = higher priority)
# Uncomment and modify based on your project structure
csc_get_file_priority() {
    local file="$1"
    local basename_file=$(basename "$file")
    
    # Project-specific priorities
    case "$basename_file" in
        README.md)         echo 1; return ;;
        CLAUDE.md)         echo 2; return ;;
        .env.example)      echo 3; return ;;
        setup.py)          echo 5; return ;;
        pyproject.toml)    echo 6; return ;;
        requirements.txt)  echo 7; return ;;
        requirements-*.txt) echo 8; return ;;
    esac
    
    case "$file" in
        ./src/__init__.py) echo 10; return ;;
        ./src/main.py)     echo 11; return ;;
        ./src/cli.py)      echo 12; return ;;
        ./src/__main__.py) echo 13; return ;;
        ./src/*.py)        echo 20; return ;;
        ./tests/*.py)      echo 80; return ;;
        ./docs/adr/*.md)   echo 40; return ;;
        ./docs/*.md)       echo 45; return ;;
        ./tests/*)         echo 80; return ;;
        ./test/*)          echo 81; return ;;
        *_test.*)          echo 82; return ;;
        *.test.*)          echo 83; return ;;
        *)                 echo 100; return ;;
    esac
}

# Custom file inclusion logic
# Uncomment and modify to customize which files are included
# csc_should_include_file() {
#     local file="$1"
#     local filename=$(basename "$file")
#     
#     # Add your custom inclusion/exclusion logic here
#     # Return 0 to include, 1 to exclude
#     
#     # Fall back to default behavior
#     default_should_include_file "$file"
# }
